name: Build iOS App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm install
          npm install @capacitor/ios

      - name: Sync Capacitor iOS
        run: |
          npx cap sync ios

      - name: Build Xcode Project
        run: |
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -sdk iphoneos -configuration Release clean build CODE_SIGNING_ALLOWED=NO
