name: Build iOS App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/ios

      -       - name: Sync Capacitor iOS
        run: |
          npx cap sync ios

        run: |
          npx cap add ios
          npx cap sync ios

      - name: Install Pods
        run: |
          cd ios/App
          pod install

      - name: Build Xcode Project
        run: |
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -sdk iphoneos -configuration Release clean build CODE_SIGNING_ALLOWED=NO
